background            #111316
foreground            #f6d0f7
cursor                #444444
selection_background  #acc9b8
color0                #000000
color8                #000000
color1                #fc5e80
color9                #fc5e80
color2                #a2f59f
color10               #a2f59f
color3                #ffd6b1
color11               #f5ffa7
color4                #85befd
color12               #95cbfe
color5                #9fa2f5
color13               #9fa2f5
color6                #fceaff
color14               #f5f29f
color7                #dfdfdf
color15               #dfdfdf
selection_foreground #161718